### ISSUE TITLE
RangeTree incorrectly reporting no overlaps

### ISSUE THREAD

**Issue by ssorallen** [moll/js-strange#2]
Take the following code:

```
const Range = require("strange");
const RangeTree = require("strange/tree");

const rangeValues = [
  [1487718000000,1487719500000],
  [1487959200000,1487991000000], // LONG one, overlaps with `overlapRange`
  [1487811600000,1487813100000],
  [1487977200000,1487978700000],
  [1487889000000,1487890500000], // Comment this one out (or any other range)
  [1487800800000,1487802300000],
  [1487887200000,1487889000000]
];
const ranges = rangeValues.map(range => new Range(range[0], range[1], '[)'));
const rangeTree = RangeTree.from(ranges);
const overlapRange = new Range(1487984400000, 1487986500000, '[)')

rangeTree.search(overlapRange);
```

The range marked "LONG" encompasses the `overlapRange` below. `rangeTree.search` incorrectly reports no overlaps. If you remove one of the unrelated, non-overlapping ranges like the one with the comment, `rangeTree.search` correctly reports "LONG" as an overlapping range.

**Comment by moll** [comment]
Hey, thanks for letting me know! There was indeed an embarrassing forgotten unification of one node's range with the rightward node's range. I'm not sure why Me^(last year) missed that.

I threw v1.7.2 out there with this fixed. Please give it a try. I'll leave this open until you report back.

Thanks again!

**Comment by ssorallen** [comment]
My use case is fixed, it looks good to me. We had to remove `strange` as a dependency when we found this because it was causing a user-facing bug, but I appreciate the prompt fix and added test case.
